# =============================================================================
# Smart Recipe Generator - Application Configuration
# =============================================================================
# 
# This file contains safe configuration defaults for development and production.
# Sensitive values are configured via environment variables:
#
# Required Environment Variables:
# - MONGODB_URI: MongoDB connection string
# - OPENROUTER_API_KEY: OpenRouter API key for LLM recipe generation
#
# Optional Environment Variables:
# - LOG_LEVEL: Application logging level (default: INFO)
# - SECURITY_LOG_LEVEL: Security logging level (default: WARN)
# - SEED_ON_START: Whether to seed database on startup (default: false)
# - OPENROUTER_BASE_URL: OpenRouter API base URL (default: https://openrouter.ai/api/v1)
# - OPENROUTER_MODEL: LLM model to use (default: google/gemini-2.5-flash)
#
# Usage:
# - Development: mvn spring-boot:run -Dspring.profiles.active=dev
# - Production: mvn spring-boot:run -Dspring.profiles.active=prod
# =============================================================================

spring:
  application:
    name: Smart Recipe Generator
  
  data:
    mongodb:
      uri: ${MONGODB_URI:}
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# OpenRouter Configuration
openrouter:
  api-key: ${OPENROUTER_API_KEY:}
  base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1}
  model: ${OPENROUTER_MODEL:google/gemini-2.5-flash}

# Recipe Algorithm Configuration  
recipe:
  score:
    min: ${SCORE_MIN:0.60}
    avg-min: ${SCORE_AVG_MIN:0.55}

# Seeding Configuration
seed:
  on-start: ${SEED_ON_START:false}

# Server Configuration
server:
  port: 8080
  forward-headers-strategy: framework



# Logging Configuration
logging:
  level:
    Assignment.Recipe_Generator: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method

# Environment-specific configurations
---
spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      Assignment.Recipe_Generator: DEBUG
      org.springframework.security: DEBUG
  seed:
    on-start: true

---
spring:
  config:
    activate:
      on-profile: prod
  logging:
    level:
      Assignment.Recipe_Generator: WARN
      org.springframework.security: WARN
  seed:
    on-start: false
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000 # 1 year

